In [16]:
import numpy as np

In [44]:
A = np.array([[1/2,1/2,0,0],
              [1/2,1/2,0,0],
              [0,0,1,0],
               [0,0,0,1]
             ])
ones_v = np.ones(3)

ones_mat = np.outer(ones_v, one_v.T) 
ones_mat = ones_mat/np.trace(ones_mat)

In [49]:
P = np.zeros((4,4))
P[0,-1] = 1
for i in range(1,4):
    P[i,i-1] = 1
P

array([[0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [69]:
import sympy as sp

In [71]:
m = 5
P = sp.zeros(m,m)
P[0,-1] = 1
for i in range(1,m):
    P[i,i-1] = 1
P

Matrix([
[0, 0, 0, 0, 1],
[1, 0, 0, 0, 0],
[0, 1, 0, 0, 0],
[0, 0, 1, 0, 0],
[0, 0, 0, 1, 0]])

In [89]:
m = 6
B = sp.eye(5) - P**m
B.rank()

4

In [80]:
P**5

Matrix([
[1, 0, 0, 0, 0],
[0, 1, 0, 0, 0],
[0, 0, 1, 0, 0],
[0, 0, 0, 1, 0],
[0, 0, 0, 0, 1]])

In [73]:
print(sp.latex(P))

\left[\begin{matrix}0 & 0 & 0 & 0 & 1\\1 & 0 & 0 & 0 & 0\\0 & 1 & 0 & 0 & 0\\0 & 0 & 1 & 0 & 0\\0 & 0 & 0 & 1 & 0\end{matrix}\right]


In [68]:
A@B@C

array([[0.5  , 0.25 , 0.125, 0.125],
       [0.5  , 0.25 , 0.125, 0.125],
       [0.   , 0.5  , 0.25 , 0.25 ],
       [0.   , 0.   , 0.5  , 0.5  ]])

In [66]:
A@B@C@A@A@C@B@B@B@B

array([[0.375, 0.25 , 0.25 , 0.125],
       [0.375, 0.25 , 0.25 , 0.125],
       [0.25 , 0.25 , 0.25 , 0.25 ],
       [0.   , 0.25 , 0.25 , 0.5  ]])

In [58]:
B = P@A@P.T
B


array([[1. , 0. , 0. , 0. ],
       [0. , 0.5, 0.5, 0. ],
       [0. , 0.5, 0.5, 0. ],
       [0. , 0. , 0. , 1. ]])

In [56]:
C = (P@P)@A@((P@P).T)
C

array([[1. , 0. , 0. , 0. ],
       [0. , 1. , 0. , 0. ],
       [0. , 0. , 0.5, 0.5],
       [0. , 0. , 0.5, 0.5]])

In [57]:
A

array([[0.5, 0.5, 0. , 0. ],
       [0.5, 0.5, 0. , 0. ],
       [0. , 0. , 1. , 0. ],
       [0. , 0. , 0. , 1. ]])

In [41]:
B = ones_mat - A

In [43]:
np.trace(B.T@B)

1.3333333333333335

In [39]:
ones_mat

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

in general for scalars in $\mathbb C$  

the fact that eigenvalues, as roots to the characteristic polynomial vary continuously with their coefficients (see discussion below) and that coefficients to the characteristic polynomial vary continuously with entries in a matrix (standard proof uses principle minors -- for an alternative proof using trace and various matrix powers see "Schurs_Inequality.ipynd"), means that eigenvalues vary continously with components of a matrix.  

**insert skeptch of proof that roots to monic polynomial vary continuously with coefficients using rudiments of planar topology, in particular winding numbers count roots, a useful inequality from Beardon, and a basic linear homotopy.**  


The fact that eigenvalues vary continuously with matrix components allows some rather nice analytical proofs of results involving eigenvalues. 

In particular it allows for some very nice proofs of results with Hermitian (inclusive of real symmetric) matrices since the eigenvalues vary contiuously with components of the matrix, but so long as we ensure Hermiticity the entire time, we know the eigenvalues must be real, and we may make use of Intermediate Value Theorem, in particular with respect to sign changes in eigenvalues implies a zero in between, which has rank implications, and we may use rank as a useful invariant along the way.  (There is some machinery buried, however, related to a theorem from Kato which ensures we can actually parameterize the eigenvalues as continuous functions... see "Eigenvalue Continuity and Gerschgorin's Theorem" by Li and Zhang  

**Sylvester's Law of Inertia**  

*note:* this closely follows the approach in Meyer's Matrix Analysis, an accordingly usese QR factorization, though we could just as easily use SVD or other spectral theorem related results  

The argument is for Hermitian $\mathbf A \in \mathbb C^{\text{n  x  n}}$, the matrix has a certain number of positive, negative and zero eigenvalues $\big(r, k, m\big)$ (where $n=r+k+m$) which is called the signature.  This is invariant under congruence transforms.  I.e. for any invertible $\mathbf B \in \mathbb C^{\text{n  x  n}}$  the signature of 

$\mathbf B^* \mathbf{AB}$ is the same as that for $\mathbf A$.  


*proof:*  

run QR factorization on $\mathbf B$ to get $\mathbf B = \mathbf Q\mathbf R$. Since $\mathbf B$ is non-singular we know the diagonal components of $\mathbf R$ are non-zero, and infact we insist they are positive (if they are not positive make use of diagonal matrix $\mathbf D$ which has all components on the unit circle such that $\big(\mathbf {DR}\big)$ has all positive components on the diagonal and see that 

$\mathbf B = \mathbf Q \mathbf R = \mathbf Q \mathbf I\mathbf R = \mathbf Q \mathbf D^* \mathbf D \mathbf R = \big(\mathbf Q \mathbf D^*\big) \big(\mathbf D \mathbf R\big) $

where $\big(\mathbf Q \mathbf D^*\big)$ is unitary and $\big(\mathbf D \mathbf R\big)$ is upper triangular with positive components on the diagonal.  Accordingly we assume WLOG that $\mathbf B = \mathbf Q\mathbf R$ with $\mathbf R$ having strictly positive entries on the diagonal.  

now consider 

$\mathbf X(\tau) := \tau \mathbf Q + (1-\tau)\mathbf Q \mathbf R = \mathbf Q\big(\tau \mathbf I + (1-\tau) \mathbf R\big)$  
for $\tau \in [0,1]$  

and notice that for any $\tau$ in the domain $\det\big(\mathbf X(\tau)\big) \neq 0$  

finally considering 

$\mathbf Y(\tau) := \mathbf X^*(\tau)\mathbf A\mathbf X(\tau)$  
or  
$\mathbf Y(\tau) = \big(\tau \mathbf I + (1-\tau) \mathbf R^*\big)\mathbf Q^* \mathbf A\mathbf Q\big(\tau \mathbf I + (1-\tau) \mathbf R\big)$  

where $\mathbf Y(\tau)$ is Hermitian for any $\tau \in [0,1]$  

in particular   
$\mathbf Y(0)= \mathbf Q^*\mathbf R^* \mathbf A\mathbf Q\mathbf R = \mathbf B^* \mathbf A\mathbf B$  
$\mathbf Y(1) = \mathbf Q^* \mathbf A\mathbf Q$  
which is similar to $\mathbf A$ and hence has the same eigenvalues as $\mathbf A$  

and for any $\tau \in [0,1]$  

$\text{rank}\big(\mathbf Y(\tau)\big) = \text{rank}\big(\mathbf A\big)$  
(because $\mathbf X(\tau)$ is always invertible)  
hence rank is a key invariant.    


The proof follows in two stages:   
*stage 1:*  consider the case where $\text{rank}\big(\mathbf A\big) = n$, i.e. our matrix of interest is invertible.  It is immediate that 
$\mathbf Y(0)$ has the same signature $\big(r, k, m\big)$ as $\mathbf Y(1)$ because if it did not then (at least) one of the eigenvalues changed sign and by intermediate value theorem there is some $\tau^* $   where   
$\text{rank}\big(\mathbf Y(\tau^*)\big) \lt n$ which contradicts the constancy of rank.  

*stage 2:* consider the case where $\text{rank}\big(\mathbf A\big) = n-m \lt n$    
There are two ways to finish.  One is again to observe that rank is an invariant for $\mathbf Y(\tau)$ and if there is a change in signature then at least one sign change occurred and some eigenvalue went from positive to negative (or vice versa) crossing zero in between.  Topologically we observe that the preimage of each and every eigenvalue taking value zero is a closed set, since the image point $[0]$ is closed.  Inevitably this means that if a 'crossing' occurred then there must be too many eigenvalues equal to zero (rank deficiency) or too few eigenvalues equal to zero (rank excess) for some $\tau^*$ when (one of) the crossing(s) ocurred.  This is conceptually simple but not so easy to write out.  

An alternative approach is the one suggested, in effect by Meyer.  Supposing $\mathbf A$ is singular, put all of its $n$ eigenvalues in a set.  There are $l$ distinct eigenvalues and call the minimum pairwise distance between these $l$ eigenvalues $d_1$.  Now re-run the argument 

$\mathbf Y(\tau, \alpha) = \mathbf X^*(\tau)\big(\mathbf A + \alpha \mathbf I\big)\mathbf X(\tau)$  

where $\alpha$ is a real valued slack parameter, initially set equal to $0$.  Supposing for a contradiction that the signature changes, we know it must have occurred by a change in positives vs negative (since zeros constant as rank is invariant) and assume WLOG that the number of positives decreases and the number of negatives decreased.  Now look at the eigenvalues of 
$\mathbf Y(0,\alpha =0)$  

and again place them in a set, computing the minimum pairwise distance between them, calling it $d_2$.  

Now set $\alpha = \alpha^* = \frac{1}{2}\min{d_1,d_2}$  

and we have a contradiciton because $\mathbf Y(0,\alpha =\alpha^*)$ has the same signature as $\mathbf Y(0,\alpha =0)$, and in particular has extra negative signs (the affine shift of eigenvalues was too small to have a sign crossing), but $\big(\mathbf A + \alpha^* \mathbf I\big)$ is non-singular so we know it cannot have had a sign change for $\tau \in [0,1]$ by the stage one argument, and in fact it has the same number of negative eigenvalues as $\mathbf A$ which is which is equal to the number of negative eigenvalues in $\mathbf Y(0,\alpha =\alpha^*)$ strictly less than the number of negative eigenvalues of $\mathbf Y(0,\alpha =\alpha^*)$, a contradiction.  

*this second stage argument could be cleaned up / streamlined a bit*  




https://cklixx.people.wm.edu/ELA-LiZhangMS4123.pdf  

the interpretation for the non-singular of $\mathbf A$  
with 

$p_(x,\tau) = \det\big(x\mathbf I - \mathbf Y(\tau)\big)$    
(or equivalently considering this as a linear combination of the minors of $\mathbf Y(\tau)$  or using newton's identity on $\mathbf Y(\tau)$)  

compute a winding number around  
the circle centered at m, with radius $m$  and $m$ chosen such that it is bigger than any possible eigenvalue of $\mathbf Y(t)$  -- e.g. using Schur's Test and operator 2 norm submultiplicativity (aka Schatten $\infty$ norm) we have  

$\Big \Vert \mathbf Y(\tau)\Big \Vert_2 $  
$= \Big \Vert \big(\tau \mathbf I + (1-\tau) \mathbf R^*\big)\mathbf Q^* \mathbf A\mathbf Q\big(\tau \mathbf I + (1-\tau) \mathbf R\big)\Big \Vert_2 $  
$\leq \Big \Vert \big(\tau \mathbf I + (1-\tau) \mathbf R\big)\Big \Vert_2^2 \Big \Vert\mathbf Q^* \mathbf A\mathbf Q\Big \Vert_2  $   
$\leq \Big\{\tau^2 \Big \Vert \mathbf I\big \Vert_2^2 + 2\tau(1-\tau) \big \Vert \mathbf I \big \Vert_2 \cdot \big \Vert \mathbf R\Big \Vert_2 + (1-\tau) \big \Vert \mathbf R \big \Vert_2^2\Big\} \big \Vert \mathbf A\big \Vert_2  $   
$\lt \Big\{1 + \big \Vert \mathbf R\Big \Vert_2 + \big \Vert \mathbf R \big \Vert_2^2\Big\} \big \Vert \mathbf A\big \Vert_2  $   (noting that $2\tau(1-\tau)\leq \frac{1}{2} \lt 1$ by $\text{GM}\leq \text{AM}$ and $\big\Vert \mathbf I \big \Vert_2 = 1$)  
$=\Big\{1 + \big \Vert \mathbf B\Big \Vert_2 + \big \Vert \mathbf B \big \Vert_2^2\Big\} \big \Vert \mathbf A\big \Vert_2  $  
and we can bound the maximal singular value of $\mathbf B$ by applying the Schur Test (i.e. maximal row magnitude sum (L1 norm of each row and take the max) times maximal column magnitude sum, then take square root -- see "Fun with trace" notebook in linear algebra folder) so $\big \Vert \mathbf B\big \Vert_2 = \sigma \leq \gamma_1$   -- and we can apply the same test/inequality to $\mathbf A$ to get $\big \Vert \mathbf A\big \Vert_2 = \sigma \leq \gamma_2$  

and selecting 

$2m:=\Big(1 + \gamma_1 + \gamma_1^2 \Big) \gamma_2$  
(Gerschgorin discs may also be used instead of the Schur test)  

gives a satisfactory result.  

note:  
an even easier approach is to use the fact that  
$\sigma \leq \big(\sum_{k=1}^n \sigma_k\big)^\frac{1}{2} = \big \Vert \mathbf M \big \Vert_F$  
and then use subadditivity and submultiplicativity of the Frobenius norm to get a very simple and crude upper bound on maximal singular value (or maximal magnitude eigenvalue)  


now we may compute the winding number around (about zero) over this closed circular path radius $m$ centered at $m$ and observe that we have a homotopy from $\tau \in [0,1]$  between  

$p_(x,0) \to p(x,1)$  

The value zero can never be in this path because 
$p_(x,\tau)$ only has real roots (Hermitian matrices generate the polynomial), and our closed path in our domain only intersects the real axis in two locations -- $2m$ and $0$ neither of which can be roots to  $p_(x,\tau)$ because the maximal eigenvalue of $p(x,\tau)$ is $\lt 2m$  and $p(0,\tau) \neq 0$  because $\text{rank}\big(\mathbf Y(\tau)\big) = n$ for any $\tau \in [0,1]$.  

This means 
$p_(x,0)$ and $p(x,1)$  
have the same winding number and hence same number of roots in this region -- and indeed on the entire positive real line (since neither may have eigenvalues $\gt 2m$).  Neither $p_(x,0)$ nor $p(x,1)$ has eigenvalues of $x=0$ and they have the same degree, so they must have the same number of negative eigenvalues as well.  
- - - -  
As in the Meyer setup, this implies the result even when $\text{rank}\big(\mathbf A\big) \lt n$.  In this case we call the smallest magnitude negative eigenvalue of $\mathbf A:= d$ (where $d \lt 0$)  

(if $\mathbf A$ has no negative eigenvalues then the desired result is immediate because $\mathbf A$ is positive semidefinite and $\mathbf B^* \mathbf{AB} = \mathbf B^* \mathbf C^* \mathbf {CB} $  so the product is positive semi-definite, and we note that rank doesn't change when multiplying by an invertible matrix, so we proceed by assuming as least one negative eigenvalue -- and there are in any case finitely many of them)  

now consider re-running the above argument on  
$\mathbf A'_k := \mathbf A + \frac{\vert d\vert}{1 + k}\mathbf I$  

This gives a density argument in the simplest form because  
$\lambda_i\big(\mathbf A'_k\big) = \lambda_i\big(\mathbf A\big) + \frac{\vert d\vert}{1 + k}$  
or  
$\lambda_i\big(\mathbf A\big) = \lambda_i\big(\mathbf A'_k\big)-\frac{\vert d\vert}{1 + k}  $  


so this tells us that we have $\text{rank}\big(\mathbf A'_k\big) = n$ for all natural numbers $k$ and that the number of negative eigenvalues of $\mathbf A'_k$ is the same as the number of negative eigenvalues of $\mathbf A$   

Application of the prior result tells us that for all negative eigenvalues of $\mathbf A'$ we have that they are still negative after the congruence transform (i.e. $\mathbf B^* \mathbf A'_k \mathbf B$) 
so for any negative eigenvalue (recalling that the multiplicities are the same for $\mathbf A'$ and $\mathbf A$) we have  

$\lambda_i\big(\mathbf A'_k\big) \lt 0 \longrightarrow \lambda_i\big(\mathbf B^* \mathbf A'_k \mathbf B\big) \lt 0 $   

This combined with the topological continuity of eigenvalues gives the desired result -- i.e. suppose for a contradiction that the number of positive eigenvalues in $\mathbf B^*\mathbf A\mathbf B$ is strictly greater than in $\mathbf A$, since $\mathbf B^*\mathbf A\mathbf B$ and $\mathbf A$ have the same rank (which implies same number of zero eigenvalues) this means some negative eigenvalue of $\mathbf A$ must have 'crossed over' into a positive one.  We can   lower bound this distance by considering 

$\lambda_{\text{min positive}}\big(\mathbf B^*\mathbf A\mathbf B\big) -  \lambda_{\text{smallest magnitude negative}}\big(\mathbf A\big) \geq \lambda_{\text{min positive}}\big(\mathbf B^*\mathbf A\mathbf B\big) - 0 = \lambda_{\text{min positive}}\big(\mathbf B^*\mathbf A\mathbf B\big) = c \gt 0 $

with  
$\lambda_{\text{min positive}}\big(\mathbf B^*\mathbf A\mathbf B\big) = c $    

since the eigenvalues vary (topologically) continuously with the components of the matrix, we select $\epsilon := \frac{c}{3} \gt 0$ which implies a $\delta \gt 0$ neighborhood where 

if $\big \Vert \mathbf B^*\mathbf A\mathbf B - \mathbf C \big \Vert_F \lt 0 \longrightarrow \text{eigenvalue difference}\big(\mathbf B^*\mathbf A\mathbf B - \mathbf C\big) \lt \epsilon$  

setting $\mathbf C:= \mathbf B^*\mathbf A'_k\mathbf B$  

$\big \Vert \mathbf B^*\mathbf A\mathbf B - \mathbf C \big \Vert_F = \frac{\vert d\vert}{1 + k}\big \Vert \mathbf B^*\mathbf B \big \Vert_F \lt \delta$   
for large enough k gives  

$c \leq \text{magnitude of eigenvalue difference}\big(\mathbf B^*\mathbf A\mathbf B - \mathbf C\big) \lt \epsilon =\frac{c}{3}$   
which is a contradiction 

(where eigenvalue difference is taken to be the minimum magnitude over all permutations, e.g. as on the 2nd page in the above cited paper from Li and Zhang-- equivalently, the metric used when proving topological eigenvalue continuity in Horn and Johnson 2nd edition of *Matrix Analysis*)  

This implies we cannot have an increase in the multiplicities of the positive eigenvalues after the congruence transform, i.e. with $\mathbf B^*\mathbf A\mathbf B$, and re-running the argument on $-\mathbf A$ implies that we cannot have an increase in the number of negative eigenvalues of $\mathbf A$ after the congruence transform. Since the number of zero eigenvalues (i.e. dimension of nullspace for hermitian matrices or equivalently: rank) is preserved under congruence transform, we have  

$\lambda_{\text{number positive}}\big(\mathbf B^*\mathbf A\mathbf B\big) \leq \lambda_{\text{number positive}}\big(\mathbf A\big)$  
$\lambda_{\text{number negative}}\big(\mathbf B^*\mathbf A\mathbf B\big) \leq \lambda_{\text{number negative}}\big(\mathbf A\big)$  
$\lambda_{\text{number zero}}\big(\mathbf B^*\mathbf A\mathbf B\big) = \lambda_{\text{number zero}}\big(\mathbf A\big)$  



and summing over the bound we have  

$n $  
$= \lambda_{\text{number positive}}\big(\mathbf B^*\mathbf A\mathbf B\big) + \lambda_{\text{number negative}}\big(\mathbf B^*\mathbf A\mathbf B\big) + \lambda_{\text{number zero}}\big(\mathbf B^*\mathbf A\mathbf B\big)$  
$\leq \lambda_{\text{number positive}}\big(\mathbf A\big) + \lambda_{\text{number negative}}\big(\mathbf A\big) + \lambda_{\text{number zero}}\big(\mathbf A\big)$  
$ = n$  

where equality is reach **iff** each inequality is an equality -- and since equality *is* reached we know the multiplicities must be the same.  



With continuity of eigenvalues in hand we can easily prove some other interesting results, in particular   
 **Cauchy's Theorem of Interlacing of Eigenvalues**      

Consider in particular an 

$\text{n  x   r}$ matrix $\mathbf Q_t$ with mutually orthnormal columns but $r\lt n$  
i.e. $\mathbf Q_t$ stands for Q "tall". 
so 

$\mathbf Q_t^* \mathbf Q_t = \mathbf I_r$  but   
$\mathbf Q_t \mathbf Q_t^* = \mathbf P$  which is a projector (hermitian and idempotent).  

the result holds in general however **we focus on the the most important special case of** $r := n-1$  

what Cauchy's Interlacing Theorem says is that the $n$ eigenvalues of $\mathbf A$ interlace with those of $(n-1)$ eigenvalues of $\big(\mathbf Q_t^* \mathbf A\mathbf Q_t\big)$, i.e.  

$\lambda_1 \geq \sigma_1 \geq \lambda_2 \geq \sigma_2 \geq .... \geq\lambda_{n-2} \geq \sigma_{n-2}\geq \lambda_{n-1}\geq \sigma_{n-1} \geq \lambda_n$  

The change in dimension between $\mathbf A$ and  $\big(\mathbf Q_t^* \mathbf A\mathbf Q_t\big)$ is awkward, though.  A better approach is to consider  

$\mathbf Q_z = \bigg[\begin{array}{c|c}\mathbf Q_t & \mathbf {0}\end{array}\bigg]$  
where the 'z' denotes zero padded  

so now we compare  

$\mathbf A$ and  $\big(\mathbf Q_z^* \mathbf A\mathbf Q_z\big)$  

now $\big(\mathbf Q_z^* \mathbf A\mathbf Q_z\big)$ has same non-zero spectra as $\big(\mathbf Q_z\mathbf Q_z^* \mathbf A\big)$ and   
$\big(\mathbf Q_z\mathbf Q_z^* \mathbf A\big) = \big(\mathbf Q_t\mathbf Q_t^* \mathbf A\big)$  
(check via outer product interpretation of matrix multiplication)   
and  

$\big(\mathbf Q_t\mathbf Q_t^* \mathbf A\big)$ has same spectra as $\big(\mathbf Q_t^* \mathbf A\mathbf Q_t\big)$ except the latter is $\text{(n-1) x (n-1)}$ and necessarily has one less zero eigenvalue for dimension reasons   

now further consider  
$\mathbf Q_z =\mathbf Q\begin{bmatrix}
\mathbf I_r & \mathbf 0\mathbf 0^T \\ 
 \mathbf 0\mathbf 0^T& \big(\mathbf 0\mathbf 0^T\big)_{n-r}
\end{bmatrix} = \mathbf Q \mathbf D$    

again focusing on  
$\mathbf Q_z =\mathbf Q\begin{bmatrix}
\mathbf I_{n-1} & \mathbf 0\mathbf 0^T \\ 
 \mathbf 0\mathbf 0^T& \big(\mathbf 0\mathbf 0^T\big)_{1}
\end{bmatrix} = \mathbf Q \mathbf D$    

where $\mathbf Q$ is the square unitary matrix and $\mathbf D$ is a diagonal matrix that is idempotent  

so we ultimately compare the spectra of  

$\mathbf A$ and  $\Big(\mathbf Q_z^* \mathbf A\mathbf Q_z\Big)  = \Big(\mathbf D \mathbf Q^* \mathbf A\mathbf Q \mathbf D\Big)= \Big(\mathbf D^* \mathbf {B D}\Big)$   

where  
$\mathbf B = \mathbf Q^* \mathbf A\mathbf Q$  
i.e. it is unitarily similar to $\mathbf A$ and so still hermitian and with the same spectrum   

*main argument*  
We start here with the **simple eigenvalue case** and build out the general proof.    

consider 

$\mathbf X(\tau) = \tau\mathbf D + (1-\tau)\mathbf I_n$  
for $\tau \in [0,1]$  

note that for $\tau \in [0,1)$ we know $\mathbf X(\tau) = \tau\mathbf D + (1-\tau)\mathbf I_n$  is non-singular (and Hermitian positive definite in particular)  

and  
$\mathbf Y(\tau) = \mathbf X(\tau)\mathbf B \mathbf X(\tau) = \mathbf X(\tau)^*\mathbf B \mathbf X(\tau)$  
so by Sylvester's Law of Interia, we know that for $\tau \in [0,1)$  
$\text{signature}\big(\mathbf Y(\tau)\big) = \text{signature}\big(\mathbf B\big) = \text{signature}\big(\mathbf A\big)$

we can then make an inference about $\mathbf D^*\mathbf B \mathbf D=\mathbf X(\tau)^*\mathbf B \mathbf X(\tau)$  at $\tau =1$ by the (topological continuity of eigenvalue.  

The argument proceeds, in effect by a for loop through each eigenvalue of $\mathbf A$ and 'pinning' them with Sylvesters Law of Inertia, so  where the $\gamma_i \in \mathbb R$ are chosen such that 

$i=1$   
$\big(\mathbf B + \gamma_i \mathbf I_n\big)$  
is positive-semi definite with a single eigenvalue equal to zero 
i.e. with signature $(n-1,0,1)$ 

$i=2$  
$\big(\mathbf B + \gamma_i \mathbf I_n\big)$  
with signature $(n-2,1,1)$  
$\vdots$  
$i=n$  
$\big(\mathbf B + \gamma_i \mathbf I_n\big)$  
with signature $(0,1,n-1)$  


and in general for $i \in \{1,2,...,n\}$  
$\big(\mathbf B + \gamma_i \mathbf I_n\big)$  
with signature $(n-i,i-1,1)$   

so again recalling 
$\mathbf Y_i(\tau) = \mathbf X(\tau)^*\big(\mathbf B + \gamma_i \mathbf I\big) \mathbf X(\tau)$
- - - -  
for $i = 1, ..., n$  

in case of i=1 
we have 
$\mathbf Y_1(\tau)$   
has signature $(n-1,0,1)$  
for $\tau \in [0,1)$   
and for $\tau = 1$  we have 
has signature  $(\leq n-1,0, \geq 1)$ 
i.e. there cannot be an increase in the number of negative eigenvalues nor can there be an increase in positive eigenvalues (both for continuity reasons and more basically that $\mathbf X(\tau=1)$ is singular.)  

This tells us that after shiting by $\gamma_1$, we know $\sigma_r$ i.e. the smallest eigenvalue for $\mathbf Q_z^*\big(\mathbf A +\gamma_1\mathbf I\big) \mathbf Q_z $ is at least zero --i.e.   
$0 = \lambda_n +\gamma_1 \leq \sigma_r +\gamma_1 \longrightarrow  \lambda_n \leq \sigma_r$  

in case of i=2  
we have 
$\mathbf Y_2(\tau)$   
has signature $(n-2,1,1)$  
for $\tau \in [0,1)$   
and for $\tau = 1$  we have 
has signature $(\leq n-2, \leq 1, \geq 1)$  
But this tells us that after shifting by $\gamma_2$ we know $\sigma_{r-1}$ i.e. the 2nd smallest eigenvalue for $\mathbf Q_z^*\big(\mathbf A +\gamma_2\mathbf I\big) \mathbf Q_z $ is at least zero and in particular  
$0 = \lambda_{n-1} +\gamma_2 \leq \sigma_{r-1} +\gamma_2\longrightarrow \lambda_{n-1}\leq \sigma_{r-1} $   
it *also* tells us that  
$\sigma_{r} +\gamma_2 \leq 0 = \lambda_{n-1} +\gamma_2 \longrightarrow \sigma_{r} \leq \lambda_{n-1} $   
*this is the interlacing property*  

*remark:*  
The reader should be able to see a pattern forming at this point.  Additionally, even though $\mathbf Q_z^*\big(\mathbf A +\gamma_2\mathbf I\big) \mathbf Q_z$ has an extra zero in it vs
$\mathbf Q_t^*\big(\mathbf A +\gamma_2\mathbf I\big) \mathbf Q_t $  
we can see this is innocuous -- because if we ignore the superflous zero, we can *still* see 
$0\leq \sigma_{r-1} +\gamma_2$ so the desired relation follows  
**insert more explanation here re:**   
$\sigma_{r} +\gamma_2 \leq 0 = \lambda_{n-1} +\gamma_2 \longrightarrow \sigma_{r} \leq \lambda_{n-1} $   


*now for the general case of* $i= k$ we have  
i=k  
we have 
$\mathbf Y_k(\tau)$   
has signature $(n-k,k-1,1)$  
for $\tau \in [0,1)$   
and for $\tau = 1$  we have 
has signature $(\leq n-k, \leq k-1, \geq 1)$  
But this tells us that after shifting by $\gamma_k$ we know $\sigma_{r-k-1}$ is at least zero and in particular  

$0 = \lambda_{n-k-1} +\gamma_k \leq \sigma_{r-k-1} +\gamma_2\longrightarrow \lambda_{n-k-1}\leq \sigma_{r-k-1} $   
*and* we know  
$ \sigma_{r-k-2} +\gamma_2 \leq 0 = \lambda_{n-k-1} +\gamma_k \longrightarrow \sigma_{r-k-2} \leq \lambda_{n-k-1} $   

*note:* 
some  obvious special handling is needed to address the largest and smallest eigenvalues since they are corner cases  

This *is* Cauchy Eigenvalue Interlacing and the argument in the case where eigenvalues are not simple (i.e. repeated roots) proceeds in an identical manner -- though it is perhaps less enjoyable.  


**corollary of Cauchy Interlacing**  

for Hermitian $\mathbf A$  with eigenvalues $\lambda_i$ 
(all matrices are assumed n x n unless otherwise noted)  

$\mathbf A + \mathbf {yy}^*$  has eigenvalues $\sigma_i$ that interlace those of $\mathbf A$, i.e.  
$\sigma_1\geq \lambda_1\geq \sigma_2\geq \lambda_2\geq....\geq \sigma_n\geq \lambda_n$  

**proof**  
we assume WLOG that $\mathbf A \succ \mathbf 0$ 
(if not, instead run the argument on $\mathbf A+\delta \mathbf I$ for large enough $\delta\gt 0$ )   

via positive definiteness we have  
$\mathbf A= \mathbf B\mathbf B^*$  
for some  
$\mathbf B = \bigg[\begin{array}{c|c|c|c} 
\mathbf b_1 & \mathbf b_2 &\cdots & \mathbf b_{n} 
\end{array}\bigg]$  
augment B to  
$\mathbf C :=\bigg[\begin{array}{c|c|c|c|c} 
\mathbf b_1 & \mathbf b_2 &\cdots & \mathbf b_{n} & \mathbf y
\end{array}\bigg]$  

then    
$\mathbf C\mathbf C^*=\mathbf A + \mathbf {yy}^*$   

and consider  
$\mathbf P:=\begin{bmatrix}\mathbf I_n\\ \mathbf {0}\end{bmatrix}$  
observing that  
$\mathbf P^*\mathbf P = \mathbf I_n$   

by Cauchy Eigenvalue Interlacing we have  
$\mathbf C^*\mathbf C \text{ interlaces } \mathbf P^*\mathbf C^*\mathbf C \mathbf P = \mathbf B^*\mathbf B$  
$\sigma_1\geq \lambda_1\geq \sigma_2\geq \lambda_2\geq....\geq \sigma_n\geq \lambda_n\geq \sigma_{n+1}=0$  

where the result follows because $\mathbf B\mathbf B^*=\mathbf A$ has the same eigenvalues as $\mathbf B^*\mathbf B$  and $\mathbf C^*\mathbf C$ has the same non-zero eigenvalues as $\mathbf C\mathbf C^*=\mathbf A + \mathbf {yy}^*$, which for dimension reasons means their eigenvalues are the same except for the 'dummy eigenvalue' $\sigma_{n+1}=0$ that was necessarily appended to the end.  


*note: "Cauchy’s Interlace Theorem forEigenvalues of Hermitian Matrices"*  
https://pdfs.semanticscholar.org/68b2/f12f71940481380503651adc8306d2d70a7e.pdf

mentions that the Cauchy Interlace Theorem has been proven via use of Sylvester's Law of Inertia...  
and cites  

page 186 of  
B. N. Parlett,The Symmetric Eigenvalue Problems, Prentice-Hall, Englewood Cliffs, NJ, 1980
