I stumbled onto this inequality while working on problem 8.7 (SVMs) in 'Learning From Data'

(all matrices are finite dimensional and real valued)

$\mathbf 1 =\begin{bmatrix}
1\\ 
1\\ 
\vdots \\ 
1
\end{bmatrix}$


$\mathbf X^T = 
\bigg[\begin{array}{c|c|c|c}
\mathbf x_1 & \mathbf x_2 &\cdots & \mathbf x_{N}
\end{array}\bigg]
$   


Thus $\mathbf{X X}^T$ is a symmetric, positive semi-definite, $N$x$N$ matrix

**claim:**

$N \cdot \text{trace}\big(\mathbf{X X}^T\big) \geq \mathbf 1^T \mathbf{X X}^T \mathbf 1 = sum \big(\mathbf{X X}^T\big)$

That is, a scalar of $N$ multiplied by the sum of the $N$ diagonal elements that come from $\text{trace}\big(\mathbf{X X}^T\big)$ must be at least as big as the sum of the entire $N^2$ elements in $\mathbf{X X}^T$

- - - - -  
*subsequent note*  
if we view the ones vector as an n x 1 matrix the above result is immediately implied by the submultiplicativity of the Frobenius norm i.e. we have  

$\sqrt{N} \cdot \text{trace}\big(\mathbf{X X}^T\big)^\frac{1}{2} = \Big \Vert \mathbf 1 \Big \Vert_F \Big \Vert \mathbf  X^T\Big \Vert_F  \geq \Big \Vert  \mathbf{X}^T\mathbf 1 \Big \Vert_F =  \text{trace}\big(\mathbf 1^T \mathbf{X X}^T \mathbf 1\big)^\frac{1}{2}  = \big(\mathbf 1^T \mathbf{X X}^T \mathbf 1\big)^\frac{1}{2}  \geq 0$   

squaring both sides then gives the result  

- - - - -  


Note that $\mathbf {X X}^T$ is symmetric and may be diagonalized.  The degenerate case where $\mathbf X$ is the zero matrix is trivially true, and excluded from this writeup.

note that $\text{trace}(\mathbf {X X}^T) =  \Sigma_{k=1}^{N} \mathbf x_k^T \mathbf x_k = \mathbf x_1^T \mathbf x_1 + \mathbf x_2^T \mathbf x_2 + ... + \mathbf x_N^T \mathbf x_N = \mathbf 1^T\big(\mathbf x_1\circ \mathbf x_1 + \mathbf x_2\circ \mathbf x_2 + ... + \mathbf x_N \circ \mathbf x_N\big) = N \mathbf 1^T E\big[ \mathbf{x} \circ \mathbf {x}\big] $

Further, notice that $\big(\mathbf 1^T \mathbf{X}\big) \big(\mathbf X^T \mathbf 1\big)= \big(\mathbf X^T \mathbf 1\big)^T \big(\mathbf X^T \mathbf 1\big) = E\big[N\mathbf x\big]^TE\big[N\mathbf x\big] = N^2 \mathbf 1^T \Big( E\big[\mathbf x\big] \circ E\big[\mathbf x\big]\Big) $

where $\circ$ denotes the Hadarmard product, and $E\big[ \big]$ denotes taking the expected value / arithmetic mean (we can think of the column vectors in $\mathbf X^T$ as being uniformly distributed, if helpful)

**proof:**  
$N \cdot \text{trace}\big(\mathbf{X X}^T\big) = N^2 \mathbf 1^T E\big[ \mathbf{x} \circ \mathbf {x}\big] \geq N^2 \mathbf 1^T \Big( E\big[\mathbf x\big] \circ E\big[\mathbf x\big]\Big)= \mathbf 1^T \mathbf{X X}^T \mathbf 1$

because: 

$ \mathbf 1^T E\big[ \mathbf{x} \circ \mathbf {x}\big] \geq \mathbf 1^T \Big( E\big[\mathbf x\big] \circ E\big[\mathbf x\big]\Big)$

equivalently:

$ \big(\mathbf{e_1 + e_2 + ... + e_N} \big)^T  E\big[ \mathbf{x} \circ \mathbf {x}\big] \geq \big(\mathbf{e_1 + e_2 + ... + e_N} \big)^T \Big( E\big[\mathbf x\big] \circ E\big[\mathbf x\big]\Big)$

where $\mathbf e_k$ denotes the kth unit standard vector (i.e. column slice of the $N$ x $N$ Identity matrix) for $k = \{1, 2, ..., N\}$

The above is true due to Jensen's Inequality.  In fact Jensen's Inequality makes an even stronger statement:

$ \mathbf e_k^T \Big(E\big[ \mathbf{x} \circ \mathbf {x}\big]\Big) \geq \mathbf e_k^T \Big( E\big[\mathbf x\big] \circ E\big[\mathbf x\big]\Big)$

which can be re-written as:

$  E\big[ \mathbf{x} \circ \mathbf {x}\big] .\geq  \Big( E\big[\mathbf x\big] \circ E\big[\mathbf x\big]\Big)$

where $.\geq$ denotes elevement-wise comparisons between the vectors.



An alternative proof uses quadratic forms.  This approach can be easily altered to accomodate complex numbers.

As in the above writeup, we banish from discussion the case of $\mathbf X$ being the zero matrix, hence $ \big \vert \big \vert \mathbf X\big \vert \big \vert_F \gt 0$.

claim: $N * \text{trace}\big(\mathbf{X X}^T\big) \geq \mathbf 1^T \mathbf{X X}^T \mathbf 1 = sum \big(\mathbf{X X}^T\big)$

where $\mathbf 1 =\begin{bmatrix}
1\\ 
1\\ 
\vdots \\ 
1
\end{bmatrix}$

$\mathbf b  := \frac{1}{\sqrt N} \mathbf 1 $ 

so $\mathbf 1^T \mathbf 1 = N = \mathbf b^T \mathbf b (\sqrt(N))^2 = 1 * N = N$

We can factorize $\big(\mathbf{X X}^T\big) = \mathbf U \mathbf D \mathbf U^T$, where $\mathbf U$ is orthogonal and $\mathbf D$ is a diagonal matrix with $\lambda_k$ in position $\mathbf D_{k,k}$

The matrix given by $\big(\mathbf{X X}^T\big)$ is symmetric, positive semi-definite, hence eigenvalues are real and non-negative. Let the eigenvalues be ordered such that $\mathbf \lambda_1 \geq \mathbf \lambda_2 \geq ... \geq \lambda_N \geq 0$


consider that $N * \text{trace}\big(\mathbf{X X}^T\big) = N * \text{trace}\big(\mathbf U \mathbf D \mathbf U^T\big) = N * \text{trace}\big(\mathbf U^T\mathbf U \mathbf D \big)= N * \text{trace}\big(\mathbf D \big) =  N * \big( \lambda_1 + \lambda_2 + ... + \lambda_N \big) $


on the other hand, consider maximizing the quadratic form 

max $\mathbf 1^T \mathbf{X X}^T \mathbf 1$  
max $\mathbf 1^T \big(\mathbf U \mathbf D \mathbf U^T\big) \mathbf 1$  
max $\sqrt(N) \mathbf b^T \big(\mathbf U \mathbf D \mathbf U^T\big) \sqrt(N) \mathbf b$  
max $N \big(\mathbf b^T \mathbf U \big) \mathbf D \big(\mathbf U^T \mathbf b \big)$  
max $N \big(\mathbf U^T \mathbf b \big)^T \mathbf D \big(\mathbf U^T \mathbf b \big)$
  
where $\mathbf U^T \mathbf b := \mathbf y$

hence $\big \vert \big \vert \mathbf y \big \vert\big \vert_2^2 = \big \vert \big \vert \mathbf U^T \mathbf b \big \vert\big \vert_2^2 = \big \vert \big \vert \mathbf b \big \vert\big \vert_2^2 = 1$

max $N \big(\mathbf y \big)^T \mathbf D \big(\mathbf y \big)$

max $N \big( \lambda_1 y_1^2 + \lambda_2 y_2^2 + ... + \lambda_N y_N^2\big)$

which is the familiar diagonalization argument for allocating all of $\mathbf y $ to $y_1$, i.e. $\mathbf y = \mathbf e_1$ (the first column slice of the N x N Identity Matrix) -- otherwise we use a familiar exchange argument to prove $\mathbf y = \mathbf e_1$ is the (weakly) dominant solution.  

Thus we have 

$N * \text{trace}\big(\mathbf{X X}^T\big) =  N * \big( \lambda_1 + \lambda_2 + ... + \lambda_N \big) \geq N \big(\lambda_1 \big)= N \big( \lambda_1 1^2 + \lambda_2 0^2 + ... + \lambda_N 0^2\big) = \mathbf e_1^T D \mathbf e_1 $

Thus we can say 

$N * \text{trace}\big(\mathbf{X X}^T\big) \gt \mathbf 1^T \mathbf{X X}^T\mathbf 1$ 

**except there is equality if and only if** $\mathbf X$ **is a rank one matrix**, where its dominant (i.e. not in the null space) left singular vector  $\propto \mathbf 1$.  More specifically, equality holds iff $\mathbf X^T$ **is a rank one matrix of the form **

$\mathbf X^T = 
\bigg[\begin{array}{c|c|c|c}
\mathbf x_1 & \mathbf x_1 &\cdots & \mathbf x_{1}
\end{array}\bigg]
= \mathbf x_1 \mathbf 1^T$   

where, as before, the ones vector, has N scalar values equal to one in it, i.e. $\mathbf 1^T \mathbf 1 = N$


Thus $\mathbf {XX}^T= \big(\mathbf {x_1 1}^T\big)^T \mathbf x_1 \mathbf 1^T =\mathbf {1 x_1}^T \mathbf x_1 \mathbf 1^T = (\mathbf x_1^T \mathbf x_1) \mathbf{11}^T$

$N * \text{trace}\big(\mathbf{X X}^T\big) = N * \text{trace}\big( (\mathbf x_1^T \mathbf x_1) * \mathbf{11}^T\big) = N *(\mathbf x_1^T \mathbf x_1) \text{trace}\big(  \mathbf1 \mathbf 1^T \big) =N *(\mathbf x_1^T \mathbf x_1) \text{trace}\big(  \mathbf1^T \mathbf 1 \big) = N^2 *(\mathbf x_1^T \mathbf x_1) $

and equivalently  
$\mathbf 1^T \mathbf{X X}^T\mathbf 1 = \mathbf 1^T  \big( \mathbf 1 \mathbf x_1^T \mathbf x_1 \mathbf 1^T\big) \mathbf 1 =  \big(\mathbf 1^T  \mathbf 1\big) \big(\mathbf x_1^T \mathbf x_1 \big) \big(\mathbf 1^T \mathbf 1\big) = (N) (\mathbf x_1^T \mathbf x_1)(N) = N^2 *(\mathbf x_1^T \mathbf x_1)$

This has a nice interpretation in terms of Jensen's Inequality, whereby 

$\mathbf 1^T \Big(E\big[ \mathbf{x} \circ \mathbf {x}\big] - E \big[\mathbf x\big] \circ E\big[\mathbf x\big]\Big) = 0$, or  $ \Big(E\big[ \mathbf{x} \circ \mathbf {x}\big] - E \big[\mathbf x\big] \circ E\big[\mathbf x\big]\Big) = \mathbf 0$ 

because by making every column in $\mathbf X^T$ the same, we homogenized the distribution such that there is now zero variance.

**Another even simpler take:**  

for some real valued vector $\mathbf x_k$, note that via the 1 trick and direct application of Cauchy Schwarz, we have:  

$\mathbf 1^T \big(\mathbf x_k \mathbf x_k^T\big) \mathbf 1 = \big(\mathbf 1^T \mathbf x_k\big) \big( \mathbf x_k^T \mathbf 1\big)  = \big(\mathbf 1^T \mathbf x_k\big)^2 \leq \big(\mathbf 1^T \mathbf 1\big) \big( \mathbf x_k^T \mathbf x_k\big) = N \big\Vert \mathbf x_k \big \Vert_2^2 $ 

using the rank one update / outer product interpretation of matrix multiplication, we have:  

$\mathbf X \mathbf X^T = \sum_{k=1}^N \mathbf x_k \mathbf x_k^T $  

combining the two we have 

$\mathbf 1^T \mathbf X \mathbf X^T \mathbf 1 = \mathbf 1^T \Big(\sum_{k=1}^N \mathbf x_k \mathbf x_k^T\Big)\mathbf 1 =  \Big(\sum_{k=1}^N \mathbf 1^T \mathbf x_k \mathbf x_k^T \mathbf 1 \Big) \leq \Big(\sum_{k=1}^N\big(\mathbf 1^T \mathbf 1\big) \big( \mathbf x_k^T \mathbf x_k\big) \Big) =  N \Big(\sum_{k=1}^N \big \Vert \mathbf x_k\big \Vert_2^2 \Big)  = N *\text{trace}\Big(\mathbf X \mathbf X^T\Big)$



**Another even simpler take:**  

using the rank one update / outer product interpretation of matrix multiplication, we have:  

$\mathbf X \mathbf X^T = \sum_{k=1}^N \mathbf x_k \mathbf x_k^T $  


for some real valued vector $\mathbf x_k$, note that via the 1 trick and direct application of Cauchy Schwarz, we have:  

$\mathbf 1^T \big(\mathbf x_k \mathbf x_k^T\big) \mathbf 1 = \big(\mathbf 1^T \mathbf x_k\big) \big( \mathbf x_k^T \mathbf 1\big)  = \big(\mathbf 1^T \mathbf x_k\big)^2 \leq \big(\mathbf 1^T \mathbf 1\big) \big( \mathbf x_k^T \mathbf x_k\big) = N \big\Vert \mathbf x_k \big \Vert_2^2 $ 

thus we can sum over the bound and see 

$\mathbf 1^T \Big(\mathbf X \mathbf X^T \big) \mathbf 1  = \mathbf 1^T \Big(\sum_{k=1}^N \mathbf x_k \mathbf x_k^T\Big) \mathbf 1 = \sum_{k=1}^N\big(\mathbf 1^T \mathbf x_k\big)^2 \leq \sum_{k=1}^N \big(\mathbf 1^T \mathbf 1\big) \big( \mathbf x_k^T \mathbf x_k\big) = \big(\mathbf 1^T \mathbf 1\big)\sum_{k=1}^N  \big( \mathbf x_k^T \mathbf x_k\big) = N \big\Vert \mathbf x_k \big \Vert_2^2 $ 



In [23]:
import numpy as np
# from scipy import fftpack
np.set_printoptions(precision = 2, linewidth=180)
from scipy.linalg import ldl
# https://scipy.github.io/devdocs/generated/scipy.linalg.ldl.html
# this is LDL^T factorization and it seems to be a relatively new addition to scipy

In [74]:
m = 50
d = 50


X = np.random.random((m,d))
X

array([[ 0.26,  0.78,  0.66, ...,  0.38,  0.1 ,  0.58],
       [ 0.37,  0.63,  0.78, ...,  0.67,  0.08,  0.44],
       [ 0.07,  0.02,  0.18, ...,  0.38,  0.77,  0.64],
       ..., 
       [ 0.24,  0.05,  0.9 , ...,  0.88,  0.81,  0.44],
       [ 0.91,  0.69,  0.91, ...,  0.02,  0.26,  0.84],
       [ 0.04,  0.71,  0.86, ...,  0.11,  0.27,  0.78]])

In [75]:
G = X.T @ X 
J = np.ones(G.shape)
ones_v = np.ones(G.shape[0])
g = np.diag(G)

g_outer = np.outer(g, ones_v)

D = g_outer + g_outer.T - 2*G

D


array([[  0.  ,   8.3 ,   8.29, ...,   7.94,  10.  ,   7.03],
       [  8.3 ,   0.  ,   7.69, ...,   6.96,   8.55,   6.82],
       [  8.29,   7.69,   0.  , ...,   9.38,  11.23,   7.25],
       ..., 
       [  7.94,   6.96,   9.38, ...,   0.  ,   7.18,   8.51],
       [ 10.  ,   8.55,  11.23, ...,   7.18,   0.  ,  10.99],
       [  7.03,   6.82,   7.25, ...,   8.51,  10.99,   0.  ]])

In [76]:
# some techniques in this cell from "miniature_7_euclidean_distance_more_mds_proof.pdf" in the 33 miniatures folder
# this nicely ties in with the PDF here 

H = np.eye(D.shape[0])-np.ones(D.shape)/D.shape[0]
B = -1/2*H @ D @ H.T 
# the transpose is for convenience of notation only, as H is symmetric 
B



array([[ 4.02, -0.23,  0.02, ...,  0.4 , -0.59,  0.6 ],
       [-0.23,  3.82,  0.21, ...,  0.79,  0.03,  0.6 ],
       [ 0.02,  0.21,  4.3 , ..., -0.18, -1.07,  0.63],
       ..., 
       [ 0.4 ,  0.79, -0.18, ...,  4.72,  1.17,  0.21],
       [-0.59,  0.03, -1.07, ...,  1.17,  4.79, -1.  ],
       [ 0.6 ,  0.6 ,  0.63, ...,  0.21, -1.  ,  4.21]])

In [93]:
L, Diagonal, perm = ldl(B)

In [94]:
L

array([[  1.00e+00,   0.00e+00,   0.00e+00, ...,   0.00e+00,   0.00e+00,   0.00e+00],
       [ -5.66e-02,   1.00e+00,   0.00e+00, ...,   0.00e+00,   0.00e+00,   0.00e+00],
       [  4.05e-03,   5.67e-02,   1.00e+00, ...,   0.00e+00,   0.00e+00,   0.00e+00],
       ..., 
       [  1.00e-01,   2.13e-01,  -5.29e-02, ...,   1.00e+00,   0.00e+00,   0.00e+00],
       [ -1.46e-01,  -1.16e-03,  -2.49e-01, ...,   7.42e-01,   1.00e+00,   0.00e+00],
       [  1.50e-01,   1.67e-01,   1.38e-01, ...,  -1.74e+00,  -1.00e+00,   1.00e+00]])

In [95]:
np.diag(Diagonal)>=0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False], dtype=bool)

In [104]:
print(Diagonal[-1,-1])
# this is a zero being registered as a a negative number which is somewhat problematic
Diagonal[Diagonal <0] = 0
# I need to double check that I did the masking correct here

0.0


In [105]:
X_tilde = L @ D **(1/2)

In [108]:
K = X_tilde.T @ X_tilde

In [110]:
np.outer(np.diag(K), ones_v) + np.outer(ones_v, np.diag(K)) - 2 * K

array([[   0.  ,   59.38,   44.28, ...,  105.08,  108.  ,   42.13],
       [  59.38,    0.  ,   48.56, ...,   85.3 ,  100.12,   42.92],
       [  44.28,   48.56,    0.  , ...,  106.94,  115.86,   33.82],
       ..., 
       [ 105.08,   85.3 ,  106.94, ...,    0.  ,   34.11,  139.32],
       [ 108.  ,  100.12,  115.86, ...,   34.11,    0.  ,  128.9 ],
       [  42.13,   42.92,   33.82, ...,  139.32,  128.9 ,    0.  ]])

In [111]:
D

array([[  0.  ,   8.3 ,   8.29, ...,   7.94,  10.  ,   7.03],
       [  8.3 ,   0.  ,   7.69, ...,   6.96,   8.55,   6.82],
       [  8.29,   7.69,   0.  , ...,   9.38,  11.23,   7.25],
       ..., 
       [  7.94,   6.96,   9.38, ...,   0.  ,   7.18,   8.51],
       [ 10.  ,   8.55,  11.23, ...,   7.18,   0.  ,  10.99],
       [  7.03,   6.82,   7.25, ...,   8.51,  10.99,   0.  ]])

In [103]:
np.linalg.norm(L @ Diagonal @ L.T - B)

1.2347603208433938e-13

In [80]:
np.sum(np.abs(np.diag(Diagonal)))

103.2140511112361

In [81]:
np.sum(np.abs(Diagonal))

103.2140511112361

In [6]:
# fft_one_way = np.fft.fft(D)
fft_one_way = np.fft.fft(D, norm='ortho')
fft_one_way
# result = np.fft.fft(np.conj(fft_one_way).T).T
result = np.fft.fft(np.conj(fft_one_way).T, norm='ortho').T

np.diag(result)


array([ 338.29 +0.00e+00j,   -8.28 -1.76e-17j,   -8.15 -1.40e-16j,   -8.43 +1.58e-16j,   -8.53 +2.81e-16j,   -7.81 +1.76e-16j,   -8.82 +7.02e-17j,   -8.12 -7.02e-17j,
         -6.69 +5.62e-16j,   -8.41 -3.16e-16j,   -8.86 +7.02e-17j,  -10.41 -1.40e-16j,   -7.07 +3.16e-16j,   -6.42 +2.81e-16j,  -10.34 +7.02e-17j,   -9.91 -1.40e-16j,
         -7.88 -8.43e-16j,  -11.43 -2.11e-16j,   -8.93 -1.40e-16j,  -10.19 +2.81e-16j,   -8.90 -7.02e-17j,  -10.19 -5.27e-17j,   -8.93 +2.72e-16j,  -11.43 +7.02e-17j,
         -7.88 +8.43e-16j,   -9.91 +2.11e-16j,  -10.34 -7.02e-17j,   -6.42 +7.02e-17j,   -7.07 -4.56e-16j,  -10.41 +5.27e-16j,   -8.86 +2.81e-16j,   -8.41 +2.11e-16j,
         -6.69 -5.62e-16j,   -8.12 -2.98e-16j,   -8.82 +3.16e-16j,   -7.81 +3.51e-16j,   -8.53 -1.22e-15j,   -8.43 -1.05e-16j,   -8.15 -3.16e-16j,   -8.28 -2.11e-16j])

In [7]:
np.real(np.diag(result)) 

array([ 338.29,   -8.28,   -8.15,   -8.43,   -8.53,   -7.81,   -8.82,   -8.12,   -6.69,   -8.41,   -8.86,  -10.41,   -7.07,   -6.42,  -10.34,   -9.91,   -7.88,  -11.43,   -8.93,
        -10.19,   -8.9 ,  -10.19,   -8.93,  -11.43,   -7.88,   -9.91,  -10.34,   -6.42,   -7.07,  -10.41,   -8.86,   -8.41,   -6.69,   -8.12,   -8.82,   -7.81,   -8.53,   -8.43,
         -8.15,   -8.28])

In [8]:
np.real(np.diag(result)) > 0

array([ True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [9]:
B = np.random.random(G.shape)
B[:,0] *= 0
B[:,0] += 1
Q, R = np.linalg.qr(B)
Q

array([[-0.16, -0.07,  0.1 , ..., -0.13,  0.18, -0.24],
       [-0.16, -0.15, -0.03, ...,  0.23,  0.16, -0.  ],
       [-0.16,  0.19, -0.18, ...,  0.03,  0.25, -0.12],
       ..., 
       [-0.16,  0.26, -0.  , ..., -0.01, -0.12, -0.25],
       [-0.16,  0.06,  0.16, ..., -0.32, -0.01, -0.19],
       [-0.16,  0.06,  0.2 , ..., -0.2 ,  0.12,  0.11]])

In [10]:
np.diag(Q.T @ D @ Q)
# grabs the diagonal of the result matrix and puts it in a vector


array([ 338.29,   -8.41,   -8.91,   -7.21,   -7.8 ,  -13.86,  -10.37,   -8.34,   -9.48,   -5.74,   -7.77,   -8.47,   -7.76,   -7.94,   -9.47,   -7.41,   -8.71,   -7.53,  -10.  ,
         -7.3 ,   -9.14,  -10.04,   -9.07,   -7.03,   -6.79,   -9.31,  -12.11,   -8.57,   -5.67,   -8.95,   -9.99,   -6.51,   -6.22,   -9.36,   -9.08,  -10.75,  -10.77,   -7.77,
         -8.55,  -10.15])

In [11]:
Q.T @ D @ Q

array([[  3.38e+02,  -5.59e+00,   6.58e+00, ...,   3.83e+00,  -1.03e-01,  -6.15e-01],
       [ -5.59e+00,  -8.41e+00,  -1.90e+00, ...,  -1.35e-01,   8.92e-01,  -1.03e+00],
       [  6.58e+00,  -1.90e+00,  -8.91e+00, ...,   1.67e-01,   4.91e-01,  -4.01e-02],
       ..., 
       [  3.83e+00,  -1.35e-01,   1.67e-01, ...,  -7.77e+00,   1.13e+00,  -2.27e-01],
       [ -1.03e-01,   8.92e-01,   4.91e-01, ...,   1.13e+00,  -8.55e+00,   9.82e-01],
       [ -6.15e-01,  -1.03e+00,  -4.01e-02, ...,  -2.27e-01,   9.82e-01,  -1.02e+01]])

In [12]:
D_similar = Q @ D @ Q.T
np.linalg.eigh(D_similar)

(array([ -2.83e+01,  -2.48e+01,  -2.19e+01,  -2.15e+01,  -2.05e+01,  -1.93e+01,  -1.80e+01,  -1.56e+01,  -1.43e+01,  -1.36e+01,  -1.30e+01,  -1.20e+01,  -1.18e+01,  -1.07e+01,
         -1.03e+01,  -9.52e+00,  -8.26e+00,  -7.90e+00,  -7.40e+00,  -6.57e+00,  -5.79e+00,  -5.13e+00,  -4.20e+00,  -3.87e+00,  -3.78e+00,  -3.44e+00,  -3.38e+00,  -2.88e+00,
         -2.35e+00,  -2.14e+00,  -1.65e+00,  -1.53e+00,  -1.42e+00,  -8.92e-01,  -8.19e-01,  -4.52e-01,  -4.20e-01,  -3.26e-01,  -2.25e-01,   3.40e+02]),
 array([[-0.01,  0.1 , -0.18, ...,  0.13, -0.23,  0.11],
        [ 0.24,  0.15, -0.14, ..., -0.22,  0.29,  0.02],
        [-0.24,  0.06,  0.28, ..., -0.04,  0.03,  0.07],
        ..., 
        [ 0.06,  0.2 ,  0.02, ...,  0.15,  0.02,  0.01],
        [-0.16, -0.19, -0.18, ..., -0.25, -0.12, -0.33],
        [ 0.01, -0.44, -0.21, ...,  0.07, -0.2 ,  0.1 ]]))

In [13]:
ones_v @ D_similar @ ones_v

-2.0605739337042905e-13

In [14]:
A = np.array([[-3,1,-3],[20,3,10],[2,-2,4]])
A

array([[-3,  1, -3],
       [20,  3, 10],
       [ 2, -2,  4]])

In [15]:
# side project here: 
G = B.T @ B
G[1:,1:] *=0 
G
# a rank two matrix...  
# I want to estimate eigs of this real symmetric matrix
eigs = np.linalg.eigvalsh(G)
print(eigs)
G

[-107.88    0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.
    0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.      0.    147.88]


array([[ 40.  ,  21.23,  18.71, ...,  21.2 ,  18.62,  17.17],
       [ 21.23,   0.  ,   0.  , ...,   0.  ,   0.  ,   0.  ],
       [ 18.71,   0.  ,   0.  , ...,   0.  ,   0.  ,   0.  ],
       ..., 
       [ 21.2 ,   0.  ,   0.  , ...,   0.  ,   0.  ,   0.  ],
       [ 18.62,   0.  ,   0.  , ...,   0.  ,   0.  ,   0.  ],
       [ 17.17,   0.  ,   0.  , ...,   0.  ,   0.  ,   0.  ]])

In [16]:
running_sum = 0
for k in range(1, G.shape[0]):
    running_sum += G[0,k] * G[k,0]
    
running_sum

15952.133329366981

In [17]:
(np.sqrt(running_sum*2) + G[0,0])/2

109.30882747345578

In [18]:
np.trace(G.T @ G) - G[0,0]**2

31904.26665873397

In [19]:
eigs[-1] * eigs[0]

-15952.133329366985

In [20]:
np.poly(A)

array([  1.,  -4.,  -3.,  18.])

In [21]:
np.linalg.eigvals(A)

array([-2. +0.00e+00j,  3. +1.19e-07j,  3. -1.19e-07j])